port: 8080

database:
  mysql:
    connection-string: root:quang@tcp(localhost:3306)/ewm?charset=utf8mb4&parseTime=True&loc=Local

security:
  cors:
    - http://localhost:8080

oauth:
  access-token-expired: 600
  refresh-token-expired: 3600
  client-id: ewm-client
  client-secret: ewmn@#123919
  jwt-secret: super-secretkey

