// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCC = "c_c"

// CC mapped from table <c_c>
type CC struct {
	ComponentID int32 `gorm:"column:component_id;primaryKey" json:"component_id"`
	CategoryID  int32 `gorm:"column:category_id;primaryKey" json:"category_id"`
}

// TableName CC's table name
func (*CC) TableName() string {
	return TableNameCC
}
