// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	CustomerID   int32     `gorm:"column:customer_id;primaryKey;autoIncrement:true" json:"customer_id"`
	CustomerName string    `gorm:"column:customer_name;not null" json:"customer_name"`
	Phone        string    `gorm:"column:phone" json:"phone"`
	Email        string    `gorm:"column:email" json:"email"`
	Address      string    `gorm:"column:address" json:"address"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	TypeInt      int32     `gorm:"column:type_int" json:"type_int"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
