// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTransferrequest = "transferrequest"

// Transferrequest mapped from table <transferrequest>
type Transferrequest struct {
	RequestID       int32     `gorm:"column:request_id;primaryKey;autoIncrement:true" json:"request_id"`
	Description     string    `gorm:"column:description;not null" json:"description"`
	TypeInt         int32     `gorm:"column:type_int;not null" json:"type_int"`
	CreationTime    time.Time `gorm:"column:creation_time;not null" json:"creation_time"`
	ExecutionTime   time.Time `gorm:"column:execution_time" json:"execution_time"`
	StatusInt       int32     `gorm:"column:status_int;not null" json:"status_int"`
	CreatorID       int32     `gorm:"column:creator_id;not null" json:"creator_id"`
	ApproverID      int32     `gorm:"column:approver_id" json:"approver_id"`
	WarehouseFromID int32     `gorm:"column:warehouse_from_id" json:"warehouse_from_id"`
	WarehouseToID   int32     `gorm:"column:warehouse_to_id" json:"warehouse_to_id"`
	CustomerID      int32     `gorm:"column:customer_id" json:"customer_id"`
}

// TableName Transferrequest's table name
func (*Transferrequest) TableName() string {
	return TableNameTransferrequest
}
