// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTransferrequestcomponent = "transferrequestcomponent"

// Transferrequestcomponent mapped from table <transferrequestcomponent>
type Transferrequestcomponent struct {
	TransferRequestComponentID int32   `gorm:"column:transfer_request_component_id;primaryKey;autoIncrement:true" json:"transfer_request_component_id"`
	RequestID                  int32   `gorm:"column:request_id;not null" json:"request_id"`
	ComponentID                int32   `gorm:"column:component_id;not null" json:"component_id"`
	Quantity                   float64 `gorm:"column:quantity;not null" json:"quantity"`
	UnitPrice                  float64 `gorm:"column:unit_price;not null" json:"unit_price"`
}

// TableName Transferrequestcomponent's table name
func (*Transferrequestcomponent) TableName() string {
	return TableNameTransferrequestcomponent
}
