// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID       int32  `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username     string `gorm:"column:username;not null" json:"username"`
	DisplayName  string `gorm:"column:display_name;not null" json:"display_name"`
	Email        string `gorm:"column:email;not null" json:"email"`
	PasswordHash string `gorm:"column:password_hash;not null" json:"password_hash"`
	StatusInt    int32  `gorm:"column:status_int;not null" json:"status_int"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
