// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBin = "bin"

// Bin mapped from table <bin>
type Bin struct {
	BinID               int       `gorm:"column:bin_id;primaryKey;autoIncrement:true" json:"bin_id"`
	LocationInWarehouse string    `gorm:"column:location_in_warehouse" json:"location_in_warehouse"`
	StatusInt           int       `gorm:"column:status_int" json:"status_int"`
	WarehouseID         int       `gorm:"column:warehouse_id" json:"warehouse_id"`
	CreatedBy           int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy           int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Bin's table name
func (*Bin) TableName() string {
	return TableNameBin
}

// BinFilter - GET request with query parameters
type BinFilter struct {
	LocationInWarehouse *string `form:"location_in_warehouse"`
	StatusInt           *int    `form:"status_int"`
	WarehouseID         *int    `form:"warehouse_id"`
	PageSize
	DateRequest
}

// BinCreate - POST request body
type BinCreate struct {
	LocationInWarehouse string `json:"location_in_warehouse" binding:"required"`
	WarehouseID         int    `json:"warehouse_id" binding:"required"`
}

// BinUpdate - PUT request body
type BinUpdate struct {
	BinID               int    `json:"bin_id" binding:"required"`
	LocationInWarehouse string `json:"location_in_warehouse"`
	StatusInt           int    `json:"status_int"`
	WarehouseID         int    `json:"warehouse_id"`
	UpdatedBy           int    `json:"updated_by"`
}

// BinResponse - Response body
type BinResponse struct {
	BinID               int       `json:"bin_id"`
	LocationInWarehouse string    `json:"location_in_warehouse"`
	StatusInt           int       `json:"status_int"`
	WarehouseID         int       `json:"warehouse_id"`
	CreatedBy           int       `json:"created_by"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedBy           int       `json:"updated_by"`
	UpdatedAt           time.Time `json:"updated_at"`
}
