// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBin = "bin"

// Bin mapped from table <bin>
type Bin struct {
	BinID               int       `gorm:"column:bin_id;primaryKey;autoIncrement:true" json:"bin_id"`
	LocationInWarehouse string    `gorm:"column:location_in_warehouse" json:"location_in_warehouse"`
	StatusInt           int       `gorm:"column:status_int" json:"status_int"`
	WarehouseID         int       `gorm:"column:warehouse_id" json:"warehouse_id"`
	CreatedBy           int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy           int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
	WarehouseName       string    `gorm:"-" json:"warehouse_name"`
}

// TableName Bin's table name
func (*Bin) TableName() string {
	return TableNameBin
}
