// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComponentCategory = "component_category"

// ComponentCategory mapped from table <component_category>
type ComponentCategory struct {
	CategoryID   int       `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	CategoryName string    `gorm:"column:category_name" json:"category_name"`
	CreatedBy    int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy    int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ComponentCategory's table name
func (*ComponentCategory) TableName() string {
	return TableNameComponentCategory
}

type ComponentCategoryFilter struct {
	CategoryID   *int    `form:"category_id"`
	CategoryName *string `form:"category_name"`
	PageSize
	DateRequest
}

type ComponentCategoryCreate struct {
	CategoryName string `json:"category_name" binding:"required"`
}

type ComponentCategoryUpdate struct {
	CategoryID   int    `json:"category_id" binding:"required"`
	CategoryName string `json:"category_name"`
	UpdatedBy    int    `json:"updated_by"`
}

type ComponentCategoryResponse struct {
	CategoryID   int       `json:"category_id"`
	CategoryName string    `json:"category_name"`
	CreatedBy    int       `json:"created_by"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedBy    int       `json:"updated_by"`
	UpdatedAt    time.Time `json:"updated_at"`
}
