// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComponentCategoryMap = "component_category_map"

// ComponentCategoryMap mapped from table <component_category_map>
type ComponentCategoryMap struct {
	ComponentID int32 `gorm:"column:component_id;primaryKey" json:"component_id"`
	CategoryID  int32 `gorm:"column:category_id;primaryKey" json:"category_id"`
}

// TableName ComponentCategoryMap's table name
func (*ComponentCategoryMap) TableName() string {
	return TableNameComponentCategoryMap
}
