// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComponentCategory = "component_category"

// ComponentCategory mapped from table <component_category>
type ComponentCategory struct {
	CategoryID   int32     `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	CategoryName string    `gorm:"column:category_name" json:"category_name"`
	CreatedBy    int32     `gorm:"column:created_by" json:"created_by"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName ComponentCategory's table name
func (*ComponentCategory) TableName() string {
	return TableNameComponentCategory
}
