// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDepartment = "department"

// Department mapped from table <department>
type Department struct {
	DepartmentID   int       `gorm:"column:department_id;primaryKey;autoIncrement:true" json:"department_id"`
	DepartmentName string    `gorm:"column:department_name;not null" json:"department_name"`
	Description    string    `gorm:"column:description" json:"description"`
	CreatedBy      int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy      int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}

type DepartmentFilter struct {
	DepartmentID   int    `json:"department_id"`
	DepartmentName string `json:"department_name"`
	Description    string `json:"description"`
	PageSize
	DateRequest
}

type DepartmentCreate struct {
	DepartmentName string `json:"department_name" binding:"required"`
	Description    string `json:"description"`
}

type DepartmentUpdate struct {
	DepartmentID   int    `json:"department_id" binding:"required"`
	DepartmentName string `json:"department_name"`
	Description    string `json:"description"`
}

type DepartmentResponse struct {
	DepartmentID   int    `json:"department_id"`
	DepartmentName string `json:"department_name"`
	Description    string `json:"description"`
}
