// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEntityFile = "entity_file"

// EntityFile mapped from table <entity_file>
type EntityFile struct {
	EntityType string `gorm:"column:entity_type;not null" json:"entity_type"`
	EntityID   int    `gorm:"column:entity_id;not null" json:"entity_id"`
	FileID     int    `gorm:"column:file_id;not null" json:"file_id"`
}

// TableName EntityFile's table name
func (*EntityFile) TableName() string {
	return TableNameEntityFile
}
