// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFile = "file"

// File mapped from table <file>
type File struct {
	FileID    int       `gorm:"column:file_id;primaryKey;autoIncrement:true" json:"file_id"`
	URL       string    `gorm:"column:url;not null" json:"url"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
