// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryAuditDetail = "inventory_audit_detail"

// InventoryAuditDetail mapped from table <inventory_audit_detail>
type InventoryAuditDetail struct {
	AuditDetailID      int32     `gorm:"column:audit_detail_id;primaryKey;autoIncrement:true" json:"audit_detail_id"`
	AuditID            int32     `gorm:"column:audit_id" json:"audit_id"`
	ComponentID        int32     `gorm:"column:component_id" json:"component_id"`
	BinID              int32     `gorm:"column:bin_id" json:"bin_id"`
	SystemQuantity     float64   `gorm:"column:system_quantity" json:"system_quantity"`
	ActualQuantity     float64   `gorm:"column:actual_quantity" json:"actual_quantity"`
	DifferenceQuantity float64   `gorm:"column:difference_quantity" json:"difference_quantity"`
	Note               string    `gorm:"column:note" json:"note"`
	CreatedBy          int32     `gorm:"column:created_by" json:"created_by"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName InventoryAuditDetail's table name
func (*InventoryAuditDetail) TableName() string {
	return TableNameInventoryAuditDetail
}
