// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryAdjustment = "inventory_adjustment"

// InventoryAdjustment mapped from table <inventory_adjustment>
type InventoryAdjustment struct {
	AdjustmentID int       `gorm:"column:adjustment_id;primaryKey;autoIncrement:true" json:"adjustment_id"`
	AuditID      int       `gorm:"column:audit_id" json:"audit_id"`
	ApprovedID   int       `gorm:"column:approved_id" json:"approved_id"`
	Description  string    `gorm:"column:description" json:"description"`
	StatusInt    int       `gorm:"column:status_int" json:"status_int"`
	Note         string    `gorm:"column:note" json:"note"`
	CreatedBy    int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy    int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InventoryAdjustment's table name
func (*InventoryAdjustment) TableName() string {
	return TableNameInventoryAdjustment
}

// InventoryAdjustmentFilter - GET request with query parameters
type InventoryAdjustmentFilter struct {
	AdjustmentID *int `form:"adjustment_id"`
	AuditID      *int `form:"audit_id"`
	StatusInt    *int `form:"status_int"`
	PageSize
	DateRequest
}

// InventoryAdjustmentCreate - POST request body
type InventoryAdjustmentCreate struct {
	AuditID     int                               `json:"audit_id" binding:"required"`
	Description string                            `json:"description"`
	Note        string                            `json:"note"`
	Details     []InventoryAdjustmentDetailCreate `json:"details"`
}

// InventoryAdjustmentUpdate - PUT request body
type InventoryAdjustmentUpdate struct {
	AdjustmentID int                               `json:"adjustment_id" binding:"required"`
	ApprovedID   int                               `json:"approved_id"`
	Description  string                            `json:"description"`
	StatusInt    int                               `json:"status_int"`
	Note         string                            `json:"note"`
	UpdatedBy    int                               `json:"updated_by"`
	Details      []InventoryAdjustmentDetailUpdate `json:"details"`
}

type InventoryAdjustmentResponse struct {
	AdjustmentID int                                 `json:"adjustment_id"`
	AuditID      int                                 `json:"audit_id"`
	ApprovedID   int                                 `json:"approved_id"`
	Description  string                              `json:"description"`
	StatusInt    int                                 `json:"status_int"`
	Note         string                              `json:"note"`
	CreatedBy    int                                 `json:"created_by"`
	CreatedAt    time.Time                           `json:"created_at"`
	UpdatedBy    int                                 `json:"updated_by"`
	UpdatedAt    time.Time                           `json:"updated_at"`
	Details      []InventoryAdjustmentDetailResponse `json:"details"`
}
