// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryAudit = "inventory_audit"

// InventoryAudit mapped from table <inventory_audit>
type InventoryAudit struct {
	AuditID     int       `gorm:"column:audit_id;primaryKey;autoIncrement:true" json:"audit_id"`
	WarehouseID int       `gorm:"column:warehouse_id" json:"warehouse_id"`
	StatusInt   int       `gorm:"column:status_int" json:"status_int"`
	Note        string    `gorm:"column:note" json:"note"`
	CreatedBy   int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy   int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InventoryAudit's table name
func (*InventoryAudit) TableName() string {
	return TableNameInventoryAudit
}
