// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryAuditDetail = "inventory_audit_detail"

// InventoryAuditDetail mapped from table <inventory_audit_detail>
type InventoryAuditDetail struct {
	AuditDetailID      int       `gorm:"column:audit_detail_id;primaryKey;autoIncrement:true" json:"audit_detail_id"`
	AuditID            int       `gorm:"column:audit_id" json:"audit_id"`
	ComponentID        int       `gorm:"column:component_id" json:"component_id"`
	BinID              int       `gorm:"column:bin_id" json:"bin_id"`
	SystemQuantity     float64   `gorm:"column:system_quantity" json:"system_quantity"`
	ActualQuantity     float64   `gorm:"column:actual_quantity" json:"actual_quantity"`
	DifferenceQuantity float64   `gorm:"column:difference_quantity" json:"difference_quantity"`
	Note               string    `gorm:"column:note" json:"note"`
	CreatedBy          int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy          int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InventoryAuditDetail's table name
func (*InventoryAuditDetail) TableName() string {
	return TableNameInventoryAuditDetail
}

// InventoryAuditDetailFilter - GET request with query parameters
type InventoryAuditDetailFilter struct {
	AuditDetailID *int `form:"audit_detail_id"`
	AuditID       *int `form:"audit_id"`
	ComponentID   *int `form:"component_id"`
	BinID         *int `form:"bin_id"`
	PageSize
	DateRequest
}

// InventoryAuditDetailCreate - POST request body
type InventoryAuditDetailCreate struct {
	AuditID        int     `json:"audit_id" binding:"required"`
	ComponentID    int     `json:"component_id" binding:"required"`
	BinID          int     `json:"bin_id" binding:"required"`
	SystemQuantity float64 `json:"system_quantity" binding:"required"`
	ActualQuantity float64 `json:"actual_quantity" binding:"required"`
}

// InventoryAuditDetailUpdate - PUT request body
type InventoryAuditDetailUpdate struct {
	AuditDetailID  int     `json:"audit_detail_id" binding:"required"`
	AuditID        int     `json:"audit_id"`
	ComponentID    int     `json:"component_id"`
	BinID          int     `json:"bin_id"`
	SystemQuantity float64 `json:"system_quantity" binding:"required"`
	ActualQuantity float64 `json:"actual_quantity" binding:"required"`
	UpdatedBy      int     `json:"updated_by"`
}

type InventoryAuditDetailResponse struct {
	AuditDetailID      int       `json:"audit_detail_id"`
	AuditID            int       `json:"audit_id"`
	ComponentID        int       `json:"component_id"`
	BinID              int       `json:"bin_id"`
	SystemQuantity     float64   `json:"system_quantity"`
	ActualQuantity     float64   `json:"actual_quantity"`
	DifferenceQuantity float64   `json:"difference_quantity"`
	Note               string    `json:"note"`
	CreatedBy          int       `json:"created_by"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedBy          int       `json:"updated_by"`
	UpdatedAt          time.Time `json:"updated_at"`
}
