// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryAdjustment = "inventory_adjustment"

// InventoryAdjustment mapped from table <inventory_adjustment>
type InventoryAdjustment struct {
	AdjustmentID int32     `gorm:"column:adjustment_id;primaryKey;autoIncrement:true" json:"adjustment_id"`
	AuditID      int32     `gorm:"column:audit_id" json:"audit_id"`
	ApprovedID   int32     `gorm:"column:approved_id" json:"approved_id"`
	Description  string    `gorm:"column:description" json:"description"`
	ApprovedTime time.Time `gorm:"column:approved_time" json:"approved_time"`
	StatusInt    int32     `gorm:"column:status_int" json:"status_int"`
	Note         string    `gorm:"column:note" json:"note"`
	CreatedBy    int32     `gorm:"column:created_by" json:"created_by"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName InventoryAdjustment's table name
func (*InventoryAdjustment) TableName() string {
	return TableNameInventoryAdjustment
}
