// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenuPermission = "menu_permission"

// MenuPermission mapped from table <menu_permission>
type MenuPermission struct {
	MenuPermissionID int `gorm:"column:menu_permission_id;primaryKey;autoIncrement:true" json:"menu_permission_id"`
	MenuID           int `gorm:"column:menu_id;not null" json:"menu_id"`
	PermissionID     int `gorm:"column:permission_id;not null" json:"permission_id"`
	IsRestricted     int `gorm:"column:is_restricted" json:"is_restricted"`
}

// TableName MenuPermission's table name
func (*MenuPermission) TableName() string {
	return TableNameMenuPermission
}
