// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenu = "menu"

// Menu mapped from table <menu>
type Menu struct {
	MenuID   int    `gorm:"column:menu_id;primaryKey;autoIncrement:true" json:"menu_id"`
	MenuName string `gorm:"column:menu_name" json:"menu_name"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
