// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	PermissionID   int32  `gorm:"column:permission_id;primaryKey;autoIncrement:true" json:"permission_id"`
	PermissionName string `gorm:"column:permission_name" json:"permission_name"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
