// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePositionHierarchy = "position_hierarchy"

// PositionHierarchy mapped from table <position_hierarchy>
type PositionHierarchy struct {
	AncestorID   int `gorm:"column:ancestor_id;primaryKey" json:"ancestor_id"`
	DescendantID int `gorm:"column:descendant_id;primaryKey" json:"descendant_id"`
	Depth        int `gorm:"column:depth;not null" json:"depth"`
}

// TableName PositionHierarchy's table name
func (*PositionHierarchy) TableName() string {
	return TableNamePositionHierarchy
}
