// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePosition = "position"

// Position mapped from table <position>
type Position struct {
	PositionID   int       `gorm:"column:position_id;primaryKey;autoIncrement:true" json:"position_id"`
	PositionName string    `gorm:"column:position_name" json:"position_name"`
	Description  string    `gorm:"column:description" json:"description"`
	CreatedBy    int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy    int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Position's table name
func (*Position) TableName() string {
	return TableNamePosition
}

type PositionFilter struct {
	PositionID   int    `json:"position_id"`
	PositionName string `json:"position_name"`
	Description  string `json:"description"`
	PageSize
	DateRequest
}

type PositionCreate struct {
	PositionName string `json:"position_name" binding:"required"`
	Description  string `json:"description"`
}

type PositionUpdate struct {
	PositionID   int    `json:"position_id" binding:"required"`
	PositionName string `json:"position_name"`
	Description  string `json:"description"`
}

type PositionResponse struct {
	PositionID   int    `json:"position_id"`
	PositionName string `json:"position_name"`
	Description  string `json:"description"`
	CreatedBy    int    `json:"created_by"`
	CreatedAt    string `json:"created_at"`
	UpdatedBy    int    `json:"updated_by"`
	UpdatedAt    string `json:"updated_at"`
}
