// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRequestPermission = "request_permission"

// RequestPermission mapped from table <request_permission>
type RequestPermission struct {
	RequestPermissionID int       `gorm:"column:request_permission_id;primaryKey;autoIncrement:true" json:"request_permission_id"`
	RequestID           int       `gorm:"column:request_id;not null" json:"request_id"`
	MenuID              int       `gorm:"column:menu_id;not null" json:"menu_id"`
	PermissionID        int       `gorm:"column:permission_id;not null" json:"permission_id"`
	Reason              string    `gorm:"column:reason" json:"reason"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName RequestPermission's table name
func (*RequestPermission) TableName() string {
	return TableNameRequestPermission
}

type RequestPermissionFilter struct {
	RequestPermissionID int `form:"request_permission_id"`
	RequestID           int `form:"request_id"`
	MenuID              int `form:"menu_id"`
	PermissionID        int `form:"permission_id"`
	PageSize
	DateRequest
}

type RequestPermissionCreate struct {
	RequestID    int    `json:"request_id", binding:"required"`
	MenuID       int    `json:"menu_id", binding:"required"`
	PermissionID int    `json:"permission_id", binding:"required"`
	Reason       string `json:"reason", binding:"required"`
}

type RequestPermissionUpdate struct {
	RequestPermissionID int    `json:"request_permission_id" binding:"required"`
	RequestID           int    `json:"request_id" binding:"required"`
	MenuID              int    `json:"menu_id" binding:"required"`
	PermissionID        int    `json:"permission_id" binding:"required"`
	Reason              string `json:"reason"`
}

type RequestPermissionResponse struct {
	RequestPermissionID int       `json:"request_permission_id"`
	RequestID           int       `json:"request_id"`
	MenuID              int       `json:"menu_id"`
	PermissionID        int       `json:"permission_id"`
	Reason              string    `json:"reason"`
	CreatedAt           time.Time `json:"created_at"`
}
