// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRequest = "request"

// Request mapped from table <request>
type Request struct {
	RequestID     int       `gorm:"column:request_id;primaryKey;autoIncrement:true" json:"request_id"`
	RequestType   string    `gorm:"column:request_type" json:"request_type"`
	Description   string    `gorm:"column:description" json:"description"`
	WarehouseID   int       `gorm:"column:warehouse_id" json:"warehouse_id"`
	BinTo         int       `gorm:"column:bin_to" json:"bin_to"`
	BinFrom       int       `gorm:"column:bin_from" json:"bin_from"`
	PerformedByID int       `gorm:"column:performed_by_id" json:"performed_by_id"`
	ApproverID    int       `gorm:"column:approver_id" json:"approver_id"`
	PartnerID     int       `gorm:"column:partner_id" json:"partner_id"`
	RequestDate   time.Time `gorm:"column:request_date" json:"request_date"`
	StatusInt     int       `gorm:"column:status_int" json:"status_int"`
	Note          string    `gorm:"column:note" json:"note"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Request's table name
func (*Request) TableName() string {
	return TableNameRequest
}
