// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRolePermission = "role_permission"

// RolePermission mapped from table <role_permission>
type RolePermission struct {
	RoleID       int `gorm:"column:role_id" json:"role_id"`
	PermissionID int `gorm:"column:permission_id" json:"permission_id"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
