// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleMenuPermission = "role_menu_permission"

// RoleMenuPermission mapped from table <role_menu_permission>
type RoleMenuPermission struct {
	RoleID       int `gorm:"column:role_id;not null" json:"role_id"`
	MenuID       int `gorm:"column:menu_id;not null" json:"menu_id"`
	PermissionID int `gorm:"column:permission_id;not null" json:"permission_id"`
}

// TableName RoleMenuPermission's table name
func (*RoleMenuPermission) TableName() string {
	return TableNameRoleMenuPermission
}
