// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemLog = "system_log"

// SystemLog mapped from table <system_log>
type SystemLog struct {
	LogID      int       `gorm:"column:log_id;primaryKey;autoIncrement:true" json:"log_id"`
	UserID     int       `gorm:"column:user_id" json:"user_id"`
	HTTPMethod string    `gorm:"column:http_method" json:"http_method"`
	Route      string    `gorm:"column:route" json:"route"`
	StatusInt  int       `gorm:"column:status_int" json:"status_int"`
	IPAddress  string    `gorm:"column:ip_address" json:"ip_address"`
	ExecutedAt time.Time `gorm:"column:executed_at" json:"executed_at"`
}

// TableName SystemLog's table name
func (*SystemLog) TableName() string {
	return TableNameSystemLog
}

type SystemLogDTO struct {
	LogID      int       `json:"log_id"`
	UserID     int       `json:"user_id"`
	HTTPMethod string    `json:"http_method"`
	Route      string    `json:"route"`
	StatusInt  int       `json:"status_int"`
	IPAddress  string    `json:"ip_address"`
	ExecutedAt time.Time `json:"executed_at"`
}
