// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRole = "user_role"

// UserRole mapped from table <user_role>
type UserRole struct {
	UserID    int       `gorm:"column:user_id;primaryKey" json:"user_id"`
	RoleID    int       `gorm:"column:role_id;primaryKey" json:"role_id"`
	CreatedBy int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
