// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID       int32     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username     string    `gorm:"column:username" json:"username"`
	DisplayName  string    `gorm:"column:display_name" json:"display_name"`
	Email        string    `gorm:"column:email" json:"email"`
	PasswordHash string    `gorm:"column:password_hash" json:"password_hash"`
	StatusInt    int32     `gorm:"column:status_int" json:"status_int"`
	CreatedBy    int32     `gorm:"column:created_by" json:"created_by"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy    int32     `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}

type UserRequest struct {
	Username    string `form:"username"`
	DisplayName string `form:"display_name"`
	Email       string `form:"email"`
	StatusInt   int32  `form:"status_int"`
	Page        int    `form:"page"`
	Size        int    `form:"size"`
}
type UserUpdate struct {
	Username string     `json:"username"`
	DisplayName string     `json:"display_name"`
	Email      string     `json:"email"`
	OldPassword string     `json:"old_password"`
	NewPassword   string    `json:"new_password"`
	StatusInt  *int32     `json:"status_int"`
	UpdatedBy  *int32     `json:"updated_by"`
	UpdatedAt  *time.Time `json:"modify_time"`
}