// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWarehouse = "warehouse"

// Warehouse mapped from table <warehouse>
type Warehouse struct {
	WarehouseID      int32     `gorm:"column:warehouse_id;primaryKey;autoIncrement:true" json:"warehouse_id"`
	WarehouseName    string    `gorm:"column:warehouse_name" json:"warehouse_name"`
	Description      string    `gorm:"column:description" json:"description"`
	PhysicalLocation string    `gorm:"column:physical_location" json:"physical_location"`
	ImageURL         string    `gorm:"column:image_url" json:"image_url"`
	CreatedBy        int32     `gorm:"column:created_by" json:"created_by"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy        int32     `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Warehouse's table name
func (*Warehouse) TableName() string {
	return TableNameWarehouse
}
