port: 8080

database:
  mysql:
    connection-string: root:quang@tcp(localhost:3306)/ewm?charset=utf8mb4&parseTime=True&loc=Local

security:
  cors:
    - http://localhost:5173

oauth:
  access-token-expired: 3600
  refresh-token-expired: 14400
  client-id: ewm-client
  client-secret: ewmn@#123919
  jwt-secret: super-secretkey



upload:
  base_path: 'C:\Users\Hiro\Documents\golang_web_api_demo\backend\upload'
  return_url: 'http://localhost:8080/uploads'


redis:
  address: "redis-14485.crce264.ap-east-1-1.ec2.cloud.redislabs.com:14485"
  username: "default"
  password: "3crEfZFoB9cM16OMuIGzXOAWhJDdzUxq"
  db: 0

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"


mail:
  host: smtp.gmail.com
  port: 587
  username: quangkt177@gmail.com
  password: cybv snos fdog dkjt
  from: quangkt177@gmail.com







# port: 8080

# security:
#   cors:
#     - http://localhost:8080
#     - http://localhost:5500
#     - http://127.0.0.1:5500

# mongodb:
#   protocol: mongodb+srv
#   username: quangkt177_db_user
#   password: fC9zfZiMj9SqNTYA
#   host: chat-application.hcogtui.mongodb.net
#   database: chat_application
#   options:
#     appName: chat-application

