// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryAdjustmentDetail = "inventory_adjustment_detail"

// InventoryAdjustmentDetail mapped from table <inventory_adjustment_detail>
type InventoryAdjustmentDetail struct {
	AdjustmentDetailID int       `gorm:"column:adjustment_detail_id;primaryKey;autoIncrement:true" json:"adjustment_detail_id"`
	AdjustmentID       int       `gorm:"column:adjustment_id" json:"adjustment_id"`
	ComponentID        int       `gorm:"column:component_id" json:"component_id"`
	BinID              int       `gorm:"column:bin_id" json:"bin_id"`
	WarehouseID        int       `gorm:"column:warehouse_id" json:"warehouse_id"`
	QuantityBefore     float64   `gorm:"column:quantity_before" json:"quantity_before"`
	QuantityAfter      float64   `gorm:"column:quantity_after" json:"quantity_after"`
	AdjustmentQuantity float64   `gorm:"column:adjustment_quantity" json:"adjustment_quantity"`
	CreatedBy          int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt          time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy          int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InventoryAdjustmentDetail's table name
func (*InventoryAdjustmentDetail) TableName() string {
	return TableNameInventoryAdjustmentDetail
}

// InventoryAdjustmentDetailFilter - GET request with query parameters
type InventoryAdjustmentDetailFilter struct {
	AdjustmentDetailID *int `form:"adjustment_detail_id"`
	AdjustmentID       *int `form:"adjustment_id"`
	PageSize
	DateRequest
}

// InventoryAdjustmentDetailCreate - POST request body
type InventoryAdjustmentDetailCreate struct {
	AdjustmentID       int     `json:"adjustment_id" binding:"required"`
	ComponentID        int     `json:"component_id" binding:"required"`
	BinID              int     `json:"bin_id" binding:"required"`
	WarehouseID        int     `json:"warehouse_id" binding:"required"`
	QuantityBefore     float64 `json:"quantity_before" binding:"required"`
	QuantityAfter      float64 `json:"quantity_after" binding:"required"`
	AdjustmentQuantity float64 `json:"adjustment_quantity" binding:"required"`
}

// InventoryAdjustmentDetailUpdate - PUT request body
type InventoryAdjustmentDetailUpdate struct {
	AdjustmentDetailID int     `json:"adjustment_detail_id" binding:"required"`
	AdjustmentID       int     `json:"adjustment_id"`
	ComponentID        int     `json:"component_id"`
	BinID              int     `json:"bin_id"`
	WarehouseID        int     `json:"warehouse_id"`
	QuantityBefore     float64 `json:"quantity_before"`
	QuantityAfter      float64 `json:"quantity_after"`
	AdjustmentQuantity float64 `json:"adjustment_quantity"`
	UpdatedBy          int     `json:"updated_by"`
}

type InventoryAdjustmentDetailResponse struct {
	AdjustmentDetailID int       `json:"adjustment_detail_id"`
	AdjustmentID       int       `json:"adjustment_id"`
	ComponentID        int       `json:"component_id"`
	BinID              int       `json:"bin_id"`
	WarehouseID        int       `json:"warehouse_id"`
	QuantityBefore     float64   `json:"quantity_before"`
	QuantityAfter      float64   `json:"quantity_after"`
	AdjustmentQuantity float64   `json:"adjustment_quantity"`
	CreatedBy          int       `json:"created_by"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedBy          int       `json:"updated_by"`
	UpdatedAt          time.Time `json:"updated_at"`
}
