// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"fmt"
	"time"
)

const TableNameInventoryAudit = "inventory_audit"

// InventoryAudit mapped from table <inventory_audit>
type InventoryAudit struct {
	AuditID     int       `gorm:"column:audit_id;primaryKey;autoIncrement:true" json:"audit_id"`
	WarehouseID int       `gorm:"column:warehouse_id" json:"warehouse_id"`
	StatusInt   int       `gorm:"column:status_int" json:"status_int"`
	Note        string    `gorm:"column:note" json:"note"`
	CreatedBy   int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy   int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName InventoryAudit's table name
func (*InventoryAudit) TableName() string {
	return TableNameInventoryAudit
}

// InventoryAuditFilter - GET request with query parameters
type InventoryAuditFilter struct {
	AuditID     *int `form:"audit_id"`
	WarehouseID *int `form:"warehouse_id"`
	StatusInt   *int `form:"status_int"`
	PageSize
	DateRequest
}

// InventoryAuditCreate - POST request body
type InventoryAuditCreate struct {
	WarehouseID int                          `json:"warehouse_id" binding:"required"`
	Note        string                       `json:"note"`
	AuditDetail []InventoryAuditDetailCreate `json:"audit_detail"`
}

// Verify validates the InventoryAuditCreate struct.
func (i *InventoryAuditCreate) Verify() error {
	if i.WarehouseID == 0 {
		return fmt.Errorf("WarehouseID is required")
	}
	return nil
}

// InventoryAuditUpdate - PUT request body
type InventoryAuditUpdate struct {
	AuditID   int    `json:"audit_id" binding:"required"`
	StatusInt int    `json:"status_int"`
	Note      string `json:"note"`
	UpdatedBy int    `json:"updated_by"`
}

// Verify validates the InventoryAuditUpdate struct.
func (i *InventoryAuditUpdate) Verify() error {
	if i.AuditID == 0 {
		return fmt.Errorf("AuditID is required")
	}
	return nil
}

type InventoryAuditResponse struct {
	AuditID     int       `json:"audit_id"`
	WarehouseID int       `json:"warehouse_id"`
	StatusInt   int       `json:"status_int"`
	Note        string    `json:"note"`
	CreatedBy   int       `json:"created_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedBy   int       `json:"updated_by"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ApprovalAudit struct {
	AuditID   int    `json:"audit_id" binding:"required"`
	StatusInt int    `json:"status_int" binding:"required"`
	Note      string `json:"note"`
}

type ConfirmAudit struct {
	AuditID   int `json:"audit_id" binding:"required"`
	StatusInt int `json:"status_int" binding:"required"`
}
