// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePositionRole = "position_role"

// PositionRole mapped from table <position_role>
type PositionRole struct {
	PositionID int       `gorm:"column:position_id" json:"position_id"`
	RoleID     int       `gorm:"column:role_id" json:"role_id"`
	CreatedBy  int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy  int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PositionRole's table name
func (*PositionRole) TableName() string {
	return TableNamePositionRole
}
