// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"fmt"
	"time"
)

const TableNameRequestDetail = "request_detail"

// RequestDetail mapped from table <request_detail>
type RequestDetail struct {
	RequestDetailID int       `gorm:"column:request_detail_id;primaryKey;autoIncrement:true" json:"request_detail_id"`
	RequestID       int       `gorm:"column:request_id" json:"request_id"`
	ComponentID     int       `gorm:"column:component_id" json:"component_id"`
	Quantity        int       `gorm:"column:quantity" json:"quantity"`
	UnitPrice       float64   `gorm:"column:unit_price" json:"unit_price"`
	BinFromID       int       `gorm:"column:bin_from_id" json:"bin_from_id"`
	BinToID         int       `gorm:"column:bin_to_id" json:"bin_to_id"`
	CreatedBy       int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy       int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RequestDetail's table name
func (*RequestDetail) TableName() string {
	return TableNameRequestDetail
}

type RequestDetailDTO struct {
	RequestID   *int     `json:"request_id"`
	ComponentID *int     `json:"component_id"`
	Quantity    *int     `json:"quantity"`
	UnitPrice   *float64 `json:"unit_price"`
	BinFromID   *int     `json:"bin_from_id"`
	BinToID     *int     `json:"bin_to_id"`
}

// RequestDetailFilter - GET request with query parameters
type RequestDetailFilter struct {
	RequestDetailID int `form:"request_detail_id"`
	RequestID       int `form:"request_id"`
	ComponentID     int `form:"component_id"`
	PageSize
	DateRequest
}

// RequestDetailCreate - POST request body
type RequestDetailCreate struct {
	RequestID   int     `json:"request_id" binding:"required"`
	ComponentID int     `json:"component_id" binding:"required"`
	Quantity    int     `json:"quantity" binding:"required"`
	UnitPrice   float64 `json:"unit_price" binding:"required"`
	BinFromID   int     `json:"bin_from_id"`
	BinToID     int     `json:"bin_to_id"`
}

// Verify validates the RequestDetailCreate struct.
func (r *RequestDetailCreate) Verify() error {
	if r.RequestID == 0 {
		return fmt.Errorf("RequestID is required")
	}
	if r.ComponentID == 0 {
		return fmt.Errorf("ComponentID is required")
	}
	if r.Quantity <= 0 {
		return fmt.Errorf("Quantity must be greater than 0")
	}
	return nil
}

// RequestDetailUpdate - PUT request body
type RequestDetailUpdate struct {
	RequestDetailID int     `json:"request_detail_id" binding:"required"`
	RequestID       int     `json:"request_id"`
	ComponentID     int     `json:"component_id"`
	Quantity        int     `json:"quantity"`
	UnitPrice       float64 `json:"unit_price"`
	BinFromID       int     `json:"bin_from_id"`
	BinToID         int     `json:"bin_to_id"`
	UpdatedBy       int     `json:"updated_by"`
}

// Verify validates the RequestDetailUpdate struct.
func (r *RequestDetailUpdate) Verify() error {
	if r.RequestDetailID == 0 {
		return fmt.Errorf("RequestDetailID is required")
	}
	return nil
}

type RequestDetailResponse struct {
	RequestDetailID int       `json:"request_detail_id"`
	RequestID       int       `json:"request_id"`
	ComponentID     int       `json:"component_id"`
	Quantity        int       `json:"quantity"`
	UnitPrice       float64   `json:"unit_price"`
	BinFromID       int       `json:"bin_from_id"`
	BinToID         int       `json:"bin_to_id"`
	CreatedBy       int       `json:"created_by"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedBy       int       `json:"updated_by"`
	UpdatedAt       time.Time `json:"updated_at"`
}
