// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"fmt"
	"time"
)

const TableNameWarehouse = "warehouse"

// Warehouse mapped from table <warehouse>
type Warehouse struct {
	WarehouseID      int       `gorm:"column:warehouse_id;primaryKey;autoIncrement:true" json:"warehouse_id"`
	WarehouseName    string    `gorm:"column:warehouse_name" json:"warehouse_name"`
	Description      string    `gorm:"column:description" json:"description"`
	PhysicalLocation string    `gorm:"column:physical_location" json:"physical_location"`
	ImageURL         string    `gorm:"column:image_url" json:"image_url"`
	CreatedBy        int       `gorm:"column:created_by" json:"created_by"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedBy        int       `gorm:"column:updated_by" json:"updated_by"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Warehouse's table name
func (*Warehouse) TableName() string {
	return TableNameWarehouse
}

// WarehouseFilter - GET request with query parameters
type WarehouseFilter struct {
	WarehouseID      *int    `form:"warehouse_id"`
	WarehouseName    *string `form:"warehouse_name"`
	PhysicalLocation *string `form:"physical_location"`
	PageSize
	DateRequest
}

// WarehouseCreate - POST request body
type WarehouseCreate struct {
	WarehouseName    string `json:"warehouse_name" binding:"required"`
	Description      string `json:"description"`
	PhysicalLocation string `json:"physical_location"`
	ImageURL         string `json:"image_url"`
}

// WarehouseCreateVerify - Verify method for WarehouseCreate
func (w *WarehouseCreate) Verify() error {
	if w.WarehouseName == "" {
		return fmt.Errorf("WarehouseName is required")
	}
	return nil
}

// WarehouseUpdate - PUT request body
type WarehouseUpdate struct {
	WarehouseID      int    `json:"warehouse_id" binding:"required"`
	WarehouseName    string `json:"warehouse_name"`
	Description      string `json:"description"`
	PhysicalLocation string `json:"physical_location"`
	ImageURL         string `json:"image_url"`
	UpdatedBy        int    `json:"updated_by"`
}

// WarehouseUpdateVerify - Verify method for WarehouseUpdate
func (w *WarehouseUpdate) Verify() error {
	if w.WarehouseID == 0 {
		return fmt.Errorf("WarehouseID is required")
	}
	return nil
}

// WarehouseResponse - Response body
type WarehouseResponse struct {
	WarehouseID      int       `json:"warehouse_id"`
	WarehouseName    string    `json:"warehouse_name"`
	Description      string    `json:"description"`
	PhysicalLocation string    `json:"physical_location"`
	ImageURL         string    `json:"image_url"`
	CreatedBy        int       `json:"created_by"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedBy        int       `json:"updated_by"`
	UpdatedAt        time.Time `json:"updated_at"`
}
