// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameBin = "bin"

// Bin mapped from table <bin>
type Bin struct {
	BinID               int32  `gorm:"column:bin_id;primaryKey;autoIncrement:true" json:"bin_id"`
	LocationInWarehouse string `gorm:"column:location_in_warehouse;not null" json:"location_in_warehouse"`
	StatusInt           int32  `gorm:"column:status_int;not null" json:"status_int"`
	WarehouseID         int32  `gorm:"column:warehouse_id;not null" json:"warehouse_id"`
}

// TableName Bin's table name
func (*Bin) TableName() string {
	return TableNameBin
}
