// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameComponent = "component"

// Component mapped from table <component>
type Component struct {
	ComponentID  int32   `gorm:"column:component_id;primaryKey;autoIncrement:true" json:"component_id"`
	MetadataJSON string  `gorm:"column:metadata_json;not null" json:"metadata_json"`
	Unit         string  `gorm:"column:unit;not null" json:"unit"`
	UnitPrice    float64 `gorm:"column:unit_price;not null" json:"unit_price"`
}

// TableName Component's table name
func (*Component) TableName() string {
	return TableNameComponent
}
