// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameComponentcategory = "componentcategory"

// Componentcategory mapped from table <componentcategory>
type Componentcategory struct {
	CategoryID   int32  `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	CategoryName string `gorm:"column:category_name;not null" json:"category_name"`
}

// TableName Componentcategory's table name
func (*Componentcategory) TableName() string {
	return TableNameComponentcategory
}
