// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameComponentbin = "componentbin"

// Componentbin mapped from table <componentbin>
type Componentbin struct {
	ComponentBinID int32   `gorm:"column:component_bin_id;primaryKey;autoIncrement:true" json:"component_bin_id"`
	Quantity       float64 `gorm:"column:quantity;not null" json:"quantity"`
	ComponentID    int32   `gorm:"column:component_id;not null" json:"component_id"`
	BinID          int32   `gorm:"column:bin_id;not null" json:"bin_id"`
}

// TableName Componentbin's table name
func (*Componentbin) TableName() string {
	return TableNameComponentbin
}
