// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameFinishedtransferrequestcomponent = "finishedtransferrequestcomponent"

// Finishedtransferrequestcomponent mapped from table <finishedtransferrequestcomponent>
type Finishedtransferrequestcomponent struct {
	FinishedTransferRequestComponentID int32   `gorm:"column:finished_transfer_request_component_id;primaryKey;autoIncrement:true" json:"finished_transfer_request_component_id"`
	RequestID                          int32   `gorm:"column:request_id;not null" json:"request_id"`
	ComponentID                        int32   `gorm:"column:component_id;not null" json:"component_id"`
	BinID                              int32   `gorm:"column:bin_id;not null" json:"bin_id"`
	Quantity                           float64 `gorm:"column:quantity;not null" json:"quantity"`
	TypeInt                            int32   `gorm:"column:type_int;not null" json:"type_int"`
}

// TableName Finishedtransferrequestcomponent's table name
func (*Finishedtransferrequestcomponent) TableName() string {
	return TableNameFinishedtransferrequestcomponent
}
