// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRole = "role"

// Role mapped from table <role>
type Role struct {
	RoleID      int32  `gorm:"column:role_id;primaryKey;autoIncrement:true" json:"role_id"`
	RoleName    string `gorm:"column:role_name;not null" json:"role_name"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
