// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUR = "u_r"

// UR mapped from table <u_r>
type UR struct {
	UserID int32 `gorm:"column:user_id;primaryKey" json:"user_id"`
	RoleID int32 `gorm:"column:role_id;primaryKey" json:"role_id"`
}

// TableName UR's table name
func (*UR) TableName() string {
	return TableNameUR
}
