// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameWarehouse = "warehouse"

// Warehouse mapped from table <warehouse>
type Warehouse struct {
	WarehouseID      int32  `gorm:"column:warehouse_id;primaryKey;autoIncrement:true" json:"warehouse_id"`
	WarehouseName    string `gorm:"column:warehouse_name;not null" json:"warehouse_name"`
	Description      string `gorm:"column:description;not null" json:"description"`
	PhysicalLocation string `gorm:"column:physical_location;not null" json:"physical_location"`
	ImageURL         string `gorm:"column:image_url" json:"image_url"`
}

// TableName Warehouse's table name
func (*Warehouse) TableName() string {
	return TableNameWarehouse
}
